env:
  browser: true
  commonjs: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
  "no-unused-vars": "off",
  "no-useless-catch": "off",
  "no-dupe-keys": "off",
  "no-undef": "off",
  "no-extra-boolean-cast": "off",
  "quotes": [2, "double", {
    avoidEscape: true,
    allowTemplateLiterals: true
  }]
}
